<?php

namespace AppBundle\Repository;

/**
 * MokslometaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MokslometaiRepository extends \Doctrine\ORM\EntityRepository
{
}
